import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GoogleOAuthProvider } from '@react-oauth/google'

import UserContextProvider from "@/context/UserContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={`${geistSans.variable} ${geistMono.variable} flex justify-center items-center h-screen`}
    >
        <GoogleOAuthProvider clientId="786638049789-52lp02ikhes6rg7v6v4b6jc850l6arrt.apps.googleusercontent.com">
            <UserContextProvider> {children}</UserContextProvider>
        </GoogleOAuthProvider>
    </body>
</html>
);
}
